dataset: "VCTK"

path:
  corpus_path: "/mnt/nfs2/speech-datasets/en/VCTK-Corpus-0.92"
  wav_tag: "mic1"
  wav_dir: "wav48_silence_trimmed"
  txt_dir: "txt"
  preprocessed_path: "./preprocessed_data/VCTK"

preprocessing:
  sanity_check: False # if Ture, then preprocess a single data and quit
  speaker_embedder: "DeepSpeaker" # support 'none', 'DeepSpeaker'
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
    skip_len: 14848
    trim_top_db: 23
    silence_audio_size: 5
    pre_emphasis: False
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
    normalize: False
